import type { Metadata } from "next";
import { Noto_Sans_Arabic, Vazirmatn } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

const vazir = Vazirmatn({ variable: "--font-vazir", subsets: ["arabic", "latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${vazir.variable} font-vazir duration-150 transition-colors`}>
        <div className="fixed right-5 bottom-10 z-50">
        </div>
        <header>
          <Navbar />
        </header>
        <main className="relative overflow-hidden"> {children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
